default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: postgres
development:
  <<: *default
  database: order_service_dev
test:
  <<: *default
  database: order_service_test
